package com.paperclip.controller;

import com.paperclip.service.UserInfoService;
import net.sf.json.JSONArray;
import net.sf.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

/*
 * get user own (create): userPaper, userNote, userDoc, userInfo, userFans
 * include
 *      get userPaper, userNote, userDoc, userInfo( user's selfinfo), messages info
 *      delete userNote, userDoc
 *      modify userInfo(e.g. password)
 *      send message
 * .js
 *      UserDocPage
 *      UserDocDetailPage
 *      UserFensPage
 *      UserNotePage
 *      UserModifyDocPage
 *      UserModifyNotePage
 *      UserPage
 *      UserSettingPage
 *      WriteDocPage
 *      HomePage
 *
 */
@CrossOrigin
@RestController
public class UserInfoController {

    @Autowired
    UserInfoService userInfoService;

    /************************************************** doc ********************************************/

    /****************
     * userDocPage  *
     ****************/
    // get user's own doc according to username( by docID, all versions of one doc only appear once )
    @RequestMapping(value = "/service/userDoc",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONArray getUserDoc(@RequestBody JSONObject data){
        return userInfoService.getUserDoc(data);
    }

    // user want to delete all versions of this doc
    @RequestMapping(value = "/service/delete/doc",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject deleteDoc( @RequestBody JSONObject data){
        return userInfoService.deleteUserDoc(data);
    }

    /************************
     * userDocDetailPage
     ***********************/
    // get user's one doc, all versions( by docID)
    @RequestMapping(value = "/service/docDetail",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONArray viewDocDetail(@RequestBody JSONObject data){
        return userInfoService.getUserDocDetail(data);
    }
    // user want to delete particular versions of this doc
    @RequestMapping(value = "/service/delete/docVersion",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject deleteDocVersion( @RequestBody JSONObject data){
        return userInfoService.deleteUserDocVersion(data);
    }

    /**************************
     *  userModifyDocPage
     *************************/
    // return the latest version
    @RequestMapping(value = "/service/modify/docDetail",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject getDocDetail(@RequestBody JSONObject data){
        return userInfoService.getDocDetail(data);
    }

    // save this doc ( date and version number are generated by backend)
    @RequestMapping(value = "/service/save/doc",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject saveDoc(@RequestBody JSONObject data){
        return userInfoService.saveDoc(data);
    }

    // add a contributer to this doc
    @RequestMapping(value = "/service/addDocContributer",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject addDocContributer(@RequestBody JSONObject data){
        return userInfoService.addDocContributer(data);
    }

    // get all docs that this user contributes ( data should contains username)
    @RequestMapping(value = "/service/contributeDoc",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONArray getContributeDoc(@RequestBody JSONObject data){
        return userInfoService.getContributeDoc(data);
    }

    /*************************
     * writeDocPage
     ************************/
    // add a new doc
    @RequestMapping(value = "/service/addDoc",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject addDoc(@RequestBody JSONObject data){
        return userInfoService.addDoc(data);
    }

    /************************************************ fans *************************************************/
    /*****************
    *  userFensPage
    ********************/
    @RequestMapping(value = "/service/userFans",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONArray getUserFans(@RequestBody JSONObject data){
        return userInfoService.getUserFans(data);
    }

    /********************************************* note ****************************************************/
    /*******************
     * userNotePage
     *******************/
    // get user's own note according to username
    @RequestMapping(value = "/service/userNote",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONArray getUserNote(@RequestBody JSONObject data){
        return userInfoService.getUserNote(data);
    }

    // user want to delete this note
    @RequestMapping(value = "/service/delete/note",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject deleteNote(@RequestBody JSONObject data){
        return userInfoService.deleteUserNote(data);
    }


    /************************
     * userModifyNotePage
     ************************/
    @RequestMapping(value = "/service/modify/noteDetail",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject getNoteDetail(@RequestBody JSONObject data){
        return userInfoService.getNoteDetail(data);
    }

    @RequestMapping(value = "/service/save/note",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject saveNote(@RequestBody JSONObject data){
        return userInfoService.saveNote(data);
    }

    /*********************
     * viewNotePage
     ********************/

    @RequestMapping(value = "/service/noteDetail",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject viewNoteDetail(@RequestBody JSONObject data){
        return userInfoService.getViewNoteDetail(data);
    }

    /***************************************************** user ************************************************************/
    /*
     * userPage
     */
    // get user own user page info
    @RequestMapping(value = "/service/hostInfo",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject getHostInfo(@RequestBody JSONObject data){
        return userInfoService.getHostInfo(data);
    }

    // get other user page info
    @RequestMapping(value = "/service/clientInfo",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject getClientInfo(@RequestBody JSONObject data){
        return userInfoService.getClientInfo(data);
    }

    /***************************
     * userSettingPage
     *****************************/
    @RequestMapping(value = "/service/modify/userinfo",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONObject modifyUserInfo(@RequestBody JSONObject data){
        return userInfoService.modifyUserInfo(data);
    }

    /********************************************** home ************************************************/
    /****************
     * homePage
     **************/
    @RequestMapping(value = "/service/homeinfo",method = RequestMethod.POST)
    public
    @ResponseBody
    JSONArray getHomeInfo(@RequestBody JSONObject data){
        return userInfoService.getHomeInfo(data);
    }
}
